Create a single 3D model of a heavy industrial black metal platter, lying perfectly flat on the ground, viewed from a 3/4 angle slightly above, Babylon.js cinematic render style, ultra high detail, dramatic rim shadowing, subtle machined surface wear and industrial precision, cool blue pulsing RGB rim lighting embedded in the outer edge with strong emissive glow, realistic heavy metal PBR material with slight oil sheen.

The platter is completely fixed in position — it can ONLY rotate smoothly around its invisible central vertical axis. No vertical movement, no tilting, no floating allowed. It must feel extremely heavy and solid.

The side facing the player has a precise horizontal slit that can emerge from the thick black rim (minimum 18cm visible depth). When activated, a satisfying mechanical garage-door effect occurs: the top half of the rim section slides upward and smoothly recedes into the platter depth, the bottom half slides downward and smoothly recedes into the platter depth, revealing visible internal mechanical depth and subtle blue RGB lighting inside the recess.

From this revealed recess, a single customizable keyboard key smoothly emerges with realistic mechanical process — deliberate, satisfying, not instantaneous (gears, slight resistance, precise alignment). The keycap is initially set to a glowing Play symbol (▶), with strong RGB lighting surrounding the key so the recess remains mostly hidden but emits a soft blue-to-cyan glow. Reference the exact mechanical style and button press animation of this key component: https://21st.dev/community/components/theutkarshmail/bluetooth-key/default — but adapted to heavy black metal industrial aesthetic with cool blue RGB accents.

Separately, a lever component emerges from another section of the rim using the exact same garage-door split mechanism. The recess for the lever remains visibly lit with RGB glow. Reference the exact mechanical style and lever switch animation of this component: https://21st.dev/community/components/theutkarshmail/lever-switch/default — adapted to heavy black metal industrial aesthetic with cool blue RGB accents.

In the exact center of the platter is a recessed circular track. Sitting inside this track is a large transparent glass sphere (diameter exactly 52cm), rendered as high-quality PBR glass with refraction, thin-film interference, and visible thickness. Inside the glass sphere is the exact celestial nebula shader effect from this reference: https://21st.dev/community/components/dhileepkumargm/celestial-sphere-shader/default. The internal effect starts with calm confident blue tones, transitions through yellows and greens, and finally to violent reds as tension increases, with increasing static, jitter, bounce, and corruption inside the sphere.

Overall composition: dark industrial void background, dramatic rim lighting only, focus on the platter and sphere, cinematic Babylon.js render, ultra-realistic mechanical details, satisfying physical motion, no text, no HUD elements, high detail, 8K, octane render quality, subtle dust particles on platter surface, perfect symmetry, mechanical precision.

Generate multiple variants with different rim thicknesses, recess depths, glass sphere transparency levels, and RGB intensity.